title = "Portfolio"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Erode, India"
favicon = "/favicon.ico"
firstName = "Sachin"
lastName = "SathiyaNarayanan"
phone = "9965780520"
showSocializations = true
showContact = false
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/sachin-s-3bb415315/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Sachin-S543"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"